### ISSUE TITLE
Where can i find the "titan" binary?

### ISSUE THREAD

**Issue by nstarke** [guyinatuxedo/nightmare#10]
Chapter 1.4: Debugging with GDB mentions a "titan"binary but no details on where to find that binary.  If you can give me a link I can create a pull request fixing the issue.  Thanks.

**Comment by guyinatuxedo** [comment]
So when I made the course, the titan binary was not included with it. That part was more or less designed to show functionality of tit. However since I've seen a lot of people actually want that binary, I'm probably just going to make a new one and include it in there. I will leave this issue open until that happens. I did push a comment to the course explaining this. Thank you and have a nice day!

**Comment by guyinatuxedo** [comment]
So thanks to a new pull request, a binary has been added to this, courtesy of deveynull.
