### ISSUE TITLE
2.14 (FB'19 Overfloat) - IDA used

### ISSUE THREAD

**Issue by ArturLukianov** [guyinatuxedo/nightmare#16]
> When we look at the chart_course disassembly in IDA, we see this: 

Not critical, but in the description mentioned that only free tools will be used.
> *    Using all open source tools 	-    All the tools used here are free and open sourced. No IDA torrent needed.

**Comment by guyinatuxedo** [comment]
So, thank you for the issue. Looking at the readme, it looks like I just said "IDA" when I meant Ghidra (this is because before that, I mentioned that I got the disassembly from ghidra). Before I worked on Nightmare I've been making write ups with IDA for a few years, so that is where the mix up came from. If I am being smooth brained and just missed something, please let me know. I just pushed a fix for this. Thank you and have a nice day!
