### ISSUE TITLE
08 bof dynamic -> Csaw19_babyboi exploit issue

### ISSUE THREAD

**Issue by obstriker** [guyinatuxedo/nightmare#22]
Hi, I tried running the exploit of this challenge and couldn't make it work.
The challenge is very simple but writeups online don't work too.
any Idea what the problem is?

**Comment by alongalky** [comment]
What error do you get? I had an issue with my OS not liking the provided libc file, when I run the binary with the given libc I get a segfault:
```bash
$ LD_PRELOAD=./libc-2.27.so ./baby_boi
Segmentation fault
```
So obviously the exploit can't work. It would probably work on some other OS (Ubuntu?), but worth adding an explanation in the write up.

Of course, maybe you have a completely different issue :).

**Comment by obstriker** [comment]
My issue was different but I do get segmentation fault if I'm running it as you did.

**Comment by alongalky** [comment]
That means your system isn't compatible with the provided libc version. My suggestion is either install an Ubuntu VM (I'm guessing you're running Kali) or follow the write up instructions to get the addresses from your local libc. See [this](https://askubuntu.com/questions/163138/how-do-i-find-what-version-of-libc-my-application-links-to) for help figuring out which version you're running and where the file is.

I still think this is an issue because the write up should include some links to explain how to deal with systems that have different libc versions, and explain about the `LD_PRELOAD` environment variable.
